name: Bug Report
description: Report a bug in Claude Agent SDK for Laravel
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below.

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Output of `php -v`
      placeholder: "8.3.1"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      description: Output of `php artisan --version`
      placeholder: "11.0"
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: Check `composer show mohamed-ashraf-elsaed/claude-agent-sdk-laravel`
      placeholder: "1.2.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output / Stack Trace
      description: Paste any relevant error output or stack trace.
      render: shell

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code to reproduce the issue.
      render: php

  - type: dropdown
    id: permission-mode
    attributes:
      label: Permission Mode
      description: Which permission mode are you using?
      options:
        - default
        - acceptEdits
        - dontAsk
        - bypassPermissions
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (OS, Claude Code CLI version, etc.).
