name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like the feature to work.
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Suggested API / Usage Example
      description: If applicable, show how the feature would be used in code.
      render: php

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area of the SDK does this affect?
      options:
        - Options / Configuration
        - Transport / CLI
        - Messages / Content
        - Streaming
        - Subagents
        - MCP Servers
        - Hooks
        - Structured Output
        - Session Management
        - Error Handling
        - Testing
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references.
